source 'https://rubygems.org'

gem 'foreman'
gem 'logger'
gem 'sinatra-rocketio'
gem 'sinatra-rocketio-linda'
gem 'sinatra-contrib'
gem 'thin'
gem 'haml'
gem 'sass'
gem 'json'
gem 'httparty'
gem 'octokit'
gem 'dalli'
gem 'hashie'
